#ifndef LIBZ_H_GENERATED_
#define LIBZ_H_GENERATED_

#define WASM_CURR_MODULE_PREFIX libz_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

#define WASM_CURR_ADD_PREFIX(x) WASM_RT_PASTE(WASM_CURR_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

#ifndef WASM_DONT_EXPORT_FUNCS
# if defined(_WIN32)
#   define FUNC_EXPORT __declspec(dllexport)
# else
#   define FUNC_EXPORT
# endif
#else
# define FUNC_EXPORT
#endif

FUNC_EXPORT wasm2c_sandbox_funcs_t WASM_CURR_ADD_PREFIX(get_wasm2c_sandbox_info)();

struct wasm2c_sandbox_t;
typedef struct wasm2c_sandbox_t wasm2c_sandbox_t;

/* import: 'wasi_snapshot_preview1' 'args_get' */
extern u32 Z_wasi_snapshot_preview1Z_args_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
extern u32 Z_wasi_snapshot_preview1Z_args_sizes_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'environ_get' */
extern u32 Z_wasi_snapshot_preview1Z_environ_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'environ_sizes_get' */
extern u32 Z_wasi_snapshot_preview1Z_environ_sizes_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'clock_res_get' */
extern u32 Z_wasi_snapshot_preview1Z_clock_res_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'clock_time_get' */
extern u32 Z_wasi_snapshot_preview1Z_clock_time_getZ_iiji(void*, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_advise' */
extern u32 Z_wasi_snapshot_preview1Z_fd_adviseZ_iijji(void*, u32, u64, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_allocate' */
extern u32 Z_wasi_snapshot_preview1Z_fd_allocateZ_iijj(void*, u32, u64, u64);
/* import: 'wasi_snapshot_preview1' 'fd_close' */
extern u32 Z_wasi_snapshot_preview1Z_fd_closeZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'fd_datasync' */
extern u32 Z_wasi_snapshot_preview1Z_fd_datasyncZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_set_flags' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_set_flagsZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_set_rights' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_set_rightsZ_iijj(void*, u32, u64, u64);
/* import: 'wasi_snapshot_preview1' 'fd_filestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_filestat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_filestat_set_size' */
extern u32 Z_wasi_snapshot_preview1Z_fd_filestat_set_sizeZ_iij(void*, u32, u64);
/* import: 'wasi_snapshot_preview1' 'fd_filestat_set_times' */
extern u32 Z_wasi_snapshot_preview1Z_fd_filestat_set_timesZ_iijji(void*, u32, u64, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_pread' */
extern u32 Z_wasi_snapshot_preview1Z_fd_preadZ_iiiiji(void*, u32, u32, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_prestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_prestat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_prestat_dir_name' */
extern u32 Z_wasi_snapshot_preview1Z_fd_prestat_dir_nameZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_pwrite' */
extern u32 Z_wasi_snapshot_preview1Z_fd_pwriteZ_iiiiji(void*, u32, u32, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_read' */
extern u32 Z_wasi_snapshot_preview1Z_fd_readZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_readdir' */
extern u32 Z_wasi_snapshot_preview1Z_fd_readdirZ_iiiiji(void*, u32, u32, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_renumber' */
extern u32 Z_wasi_snapshot_preview1Z_fd_renumberZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_seek' */
extern u32 Z_wasi_snapshot_preview1Z_fd_seekZ_iijii(void*, u32, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_sync' */
extern u32 Z_wasi_snapshot_preview1Z_fd_syncZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'fd_tell' */
extern u32 Z_wasi_snapshot_preview1Z_fd_tellZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_write' */
extern u32 Z_wasi_snapshot_preview1Z_fd_writeZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_create_directory' */
extern u32 Z_wasi_snapshot_preview1Z_path_create_directoryZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_filestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_path_filestat_getZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_filestat_set_times' */
extern u32 Z_wasi_snapshot_preview1Z_path_filestat_set_timesZ_iiiiijji(void*, u32, u32, u32, u32, u64, u64, u32);
/* import: 'wasi_snapshot_preview1' 'path_link' */
extern u32 Z_wasi_snapshot_preview1Z_path_linkZ_iiiiiiii(void*, u32, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_open' */
extern u32 Z_wasi_snapshot_preview1Z_path_openZ_iiiiiijjii(void*, u32, u32, u32, u32, u32, u64, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_readlink' */
extern u32 Z_wasi_snapshot_preview1Z_path_readlinkZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_remove_directory' */
extern u32 Z_wasi_snapshot_preview1Z_path_remove_directoryZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_rename' */
extern u32 Z_wasi_snapshot_preview1Z_path_renameZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_symlink' */
extern u32 Z_wasi_snapshot_preview1Z_path_symlinkZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_unlink_file' */
extern u32 Z_wasi_snapshot_preview1Z_path_unlink_fileZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'poll_oneoff' */
extern u32 Z_wasi_snapshot_preview1Z_poll_oneoffZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'proc_exit' */
extern void Z_wasi_snapshot_preview1Z_proc_exitZ_vi(void*, u32);
/* import: 'wasi_snapshot_preview1' 'proc_raise' */
extern u32 Z_wasi_snapshot_preview1Z_proc_raiseZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'sched_yield' */
extern u32 Z_wasi_snapshot_preview1Z_sched_yieldZ_iv(void*);
/* import: 'wasi_snapshot_preview1' 'random_get' */
extern u32 Z_wasi_snapshot_preview1Z_random_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'sock_recv' */
extern u32 Z_wasi_snapshot_preview1Z_sock_recvZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'sock_send' */
extern u32 Z_wasi_snapshot_preview1Z_sock_sendZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'sock_shutdown' */
extern u32 Z_wasi_snapshot_preview1Z_sock_shutdownZ_iii(void*, u32, u32);

FUNC_EXPORT u32 w2c_signature_mismatch_lseek(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_undefined_weak___wasilibc_find_relpath_alloc(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT void w2c__start(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_adler32_z(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_adler32(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_adler32_combine(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_adler32_combine64(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_get_crc_table(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_crc32_z(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_crc32(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_crc32_combine(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_crc32_combine_(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_crc32_combine64(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gzclose(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzread(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gz_read(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gz_fetch(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gz_decomp(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzfread(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_gzgetc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzgetc_(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzungetc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzgets(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gz_look(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzdirect(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzclose_r(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_inflateBackInit_(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_inflateBack(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_inflateBackEnd(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_inflateResetKeep(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_inflateReset(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_inflateReset2(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_inflateInit2_(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_inflateInit_(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_inflatePrime(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_inflate(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_updatewindow(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_inflateEnd(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_inflateGetDictionary(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_inflateSetDictionary(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_inflateGetHeader(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_inflateSync(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_inflateSyncPoint(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_inflateCopy(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_inflateUndermine(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_inflateValidate(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_inflateMark(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_inflateCodesUsed(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c__tr_init(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_init_block(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c__tr_stored_block(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void w2c__tr_flush_bits(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c__tr_align(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c__tr_flush_block(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void w2c_build_tree(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_compress_block(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_send_tree(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c__tr_tally(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_zlibVersion(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_zlibCompileFlags(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_zError(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_zcalloc(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_zcfree(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_compress2(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_compress(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_compressBound(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_deflateInit_(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_deflateInit2_(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_deflateEnd(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_deflateReset(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_deflateResetKeep(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_deflateSetDictionary(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_fill_window(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_deflateGetDictionary(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_deflateSetHeader(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_deflatePending(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_deflatePrime(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_deflateParams(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_deflate(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_slide_hash(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_flush_pending(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_deflate_stored(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_deflate_huff(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_deflate_rle(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_deflateTune(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_deflateBound(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_deflateCopy(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_deflate_fast(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_longest_match(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_deflate_slow(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzopen(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gz_open(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gzopen64(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzdopen(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzbuffer(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzrewind(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzseek64(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_gz_error(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gzseek(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gztell64(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gztell(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzoffset64(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzoffset(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzeof(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzerror(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_gzclearerr(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gzwrite(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gz_write(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gz_init(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_gz_comp(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzfwrite(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_gzputc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzputs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzvprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gzprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gzflush(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_gzsetparams(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_gzclose_w(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_inflate_fast(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_inflate_table(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_uncompress2(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_uncompress(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_malloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_dlmalloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_dlfree(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_calloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_realloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_dispose_chunk(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_posix_memalign(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_internal_memalign(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_aligned_alloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_malloc_usable_size(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_read(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_close(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_write(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_sbrk(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c__Exit(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_internal_register_preopened_fd(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fdopendir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_sel_true(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_open(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_access(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_readlink(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_stat(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_lstat(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_utime(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_unlink(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_rmdir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_remove(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_mkdir(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_opendir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_scandir(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_symlink(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_link(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_rename(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_abort(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_strerror(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_dummy(wasm2c_sandbox_t* const);
FUNC_EXPORT void w2c_exit(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_vsnprintf(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_sn_write(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_printf(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_snprintf(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_writev(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fwrite(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fputs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_vfprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_printf_core(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT void w2c_pop_arg(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_pad(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT void w2c_long_double_not_supported(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_strlen(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_strdup(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_memcpy(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_memset(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strnlen(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memcmp(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_memchr(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_dummy_1(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_qsort(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void w2c_trinkle(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_wctomb(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_wcrtomb(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT f64 w2c_frexp(wasm2c_sandbox_t* const, f64, u32);

#ifdef __cplusplus
}
#endif

#endif  /* LIBZ_H_GENERATED_ */
